### ISSUE TITLE
'RequestDatabase' object has no attribute 'logging'

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.aleph_link_export#11]
Some exception arrived after LinkUpdateRequest has been sent:

```
ComponentLookupError: ((<AMQPFolder at /edeposit/amqp>, AMQPError(headers={'exception_type': "<type 'exceptions.AttributeError'>", 'exception': "'RequestDatabase' object has no attribute 'logging'", 'traceback': 'Traceback (most recent call last):\n  File "/usr/lib\
/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 142, in onMessageReceived\n    self.get_sendback(uuid, key)\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/aleph_link_export/__init__.py", line 69, in reactToAMQPMessage\n    return _send_response\
s(send_back)\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/aleph_link_export/__init__.py", line 27, in _send_responses\n    responses = link_export.collect_responses()\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/aleph_link_export/link_export.p\
y", line 52, in collect_responses\n    resp = REQUEST_DATABASE.get_responses()\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/aleph_link_export/request_database.py", line 149, in get_responses\n    self._process_responses()\n  File "/usr/lib/python2.7/site\
-packages/edeposit/amqp/aleph_link_export/request_database.py", line 134, in _process_responses\n    self._add_response(LinkUpdateResponse(**result))\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/aleph_link_export/request_database.py", line 106, in _add_r\
esponse\n    self.log("Received response session_id(%s)." % response.session_id)\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/aleph_link_export/request_database.py", line 63, in log\n    if not self.logging:\nAttributeError: \'RequestDatabase\' object ha\
s no attribute \'logging\'', 'exception_name': 'AttributeError', 'UUID': '2015-09-29 15:00:01.973321'}, exception="'RequestDatabase' object has no attribute 'logging'", payload="'RequestDatabase' object has no attribute 'logging'", exception_name='AttributeError'))\
, <InterfaceClass edeposit.content.amqp.IAMQPHandler>, u'')
```

**Comment by jstavel** [comment]
(blocks edeposit/edeposit#575)

**Comment by jstavel** [comment]
Maybe I should update even application side of an communication channel.
So I will upgrade even edeposit application.

**Comment by jstavel** [comment]
It is a report from amqp service.
So there is no need to upgrade client side. But I will do it. For sure.

**Comment by Bystroushaak** [comment]
It is the problem of shelve database. I will fix it.

**Comment by Bystroushaak** [comment]
It should be fixed now.
