### ISSUE TITLE
 payload="u'LinkDescription'", exception_name='KeyError')

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.aleph_link_export#15]
Ahoj Jardo hlasim vyjimku. Nerozumim ji.

```
<- AMQP Exception for:  http://edeposit-aplikace.nkp.cz/producents/ostre-nakladatelstvi-c-16-2013-pdf-a1b/epublications/prace-s-empirickymi-daty-2/thumbnail.pdf
AMQPError(headers={'exception_type': "<type 'exceptions.KeyError'>", 'exception': 'LinkDescription', 'traceback': 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 141, in onMessageReceived\n    seriali\
zers.deserialize(body, self.globals),\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/serializers/serializers.py", line 175, in deserialize\n    return _deserializeNT(json.loads(json_str), glob)\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/serial\
izers/serializers.py", line 134, in _deserializeNT\n    **dict(zip(data, _deserializeNT(data.values(), glob)))\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/serializers/serializers.py", line 122, in _deserializeNT\n    return [_deserializeNT(item, glob) f\
or item in data]\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/serializers/serializers.py", line 122, in _deserializeNT\n    return [_deserializeNT(item, glob) for item in data]\n  File "/usr/lib/python2.7/site-packages/edeposit/amqp/serializers/serialize\
rs.py", line 138, in _deserializeNT\n    return globals()[class_name](\nKeyError: u\'LinkDescription\'', 'exception_name': 'KeyError', 'UUID': '{"context_UID": "e900d1ddc1e64b6c93066b76cf864577", "session_data": {"isbn": "978-80-246-2801-1"}}'}, exception='LinkDesc\
ription', payload="u'LinkDescription'", exception_name='KeyError')
```

(blocks #575 #632)

**Comment by jstavel** [comment]
Mozna je potreba udelat upgrade i baliku edeposit.amqp.serializers.
Jdu to zkusit.

**Comment by jstavel** [comment]
tak asi uz mam chybu - udelal jsem upgrade na edeposit-test.
Spravne se ma udelat na edeposit-storage. Hm.

**Comment by jstavel** [comment]
Takze uz to funguje.
Chyba byla v tom, ze jsem provedl upgrade na stroji edeposit-test.
Aleph link export pro ostry provoz bezi na stroji edeposit-storage.

Provedl jsem upgrade i tam a uz je zprava prijata.

Uzaviram.

**Comment by Bystroushaak** [comment]
Super :)
