### ISSUE TITLE
NoneType is not iterable when malformed msg arrives

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.aleph_link_export#8]
```
edeposit-aplikace:/opt/edeposit # sudo su - aleph_export
aleph_export@edeposit-aplikace:~> edeposit_amqp_aleph_link_exportd.py start --foreground
Traceback (most recent call last):
  File "/usr/bin/edeposit_amqp_aleph_link_exportd.py", line 85, in <module>
    main(args)
  File "/usr/bin/edeposit_amqp_aleph_link_exportd.py", line 52, in main
    daemon.run()
  File "/usr/lib/python2.7/site-packages/edeposit/amqp/daemonwrapper.py", line 68, in run
    self.body()
  File "/usr/lib/python2.7/site-packages/edeposit/amqp/pikadaemon.py", line 65, in body
    if self.onMessageReceived(method_frame, properties, body):
  File "/usr/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 128, in onMessageReceived
    if "UUID" not in properties.headers:
TypeError: argument of type 'NoneType' is not iterable
aleph_export@edeposit-aplikace:~> 
```

Applications stop running at supervisord with status:

```
aleph-link-exportd               FATAL     Exited too quickly (process log may have details)
```

I will ensure eDeposit sends msg with UUID at the moment.
I cannot ensure someone sends only valid msgs in the future.

Happy pythoning,
Jan

**Comment by jstavel** [comment]
(see edeposit/edeposit#599)
